<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend>
    <p>
    <div class="field regulation">
        <label for="regulation" class="label"><span><?php /* @escapeNotVerified */
                echo __('Istagram Account') ?></span></label>
        <div class="control">
            <input type="text" name="igaddress" id="igaddress" title="<?php /* @escapeNotVerified */ echo __('Instagram Account') ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
    </p>
</fieldset>