<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= __('Nomor Order: <b>%1.</b>', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
            <p><?= __('Product: <b>%1.</b>', sprintf('%s', $block->escapeHtml($block->getOrderItem()))) ?></p>
            <p>Jumlah Yang harus dipayar: <?php echo number_format($block->getTotalAmount(),0);?></p>
            <p>Segera Lakukan pembayaran anda sebelum stock Habis</p>
            <br/>
            Order Sobat sudah kami terima <br/>
            Segera lakukan pembayaran dalam waktu:
            <h2><p id="demo"></p></h2>
            <?php $date_bayar_label=date('d M Y h:i', time() + 111600); ?>
            <?php $date_bayar_js=date('M d, Y h:i:s', time() + 111600); ?>
            <p><h3>(<b>Sebelum <?php echo $date_bayar_label;?> WIB</b>)</h3></p>
            
            <?php

            if ($block->getPaymentMethod()=="banktransfer"){
            echo "<p>Metode pembayaran yg digunakan : Bank Transfer</p>";
            echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('petunjuk_transfer')
                    ->toHtml();
            }
            if ($block->getPaymentMethod()=="cashondelivery"){

            echo "<p>Metode pembayaran yg digunakan : Bayar Tunai(Cash)</p>";
                echo $this->getLayout()
                        ->createBlock('Magento\Cms\Block\Block')
                        ->setBlockId('petunjuk_cash')
                        ->toHtml();
                }
            ?>
            

<script>
// Set the date we're counting down to
var countDownDate = new Date("<?php echo $date_bayar_js;?>").getTime();

// Update the count down every 1 second
var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();
    
  // Find the distance between now and the count down date
  var distance = countDownDate - now;
    
  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    
  // Output the result in an element with id="demo"
  //document.getElementById("demo").innerHTML = days + "d " + hours + "h "
  //+ minutes + "m " + seconds + "s ";
  document.getElementById("demo").innerHTML =  hours + "Jam "
  + minutes + "Menit " + seconds + "Detik ";
    
  // If the count down is over, write some text 
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "EXPIRED";
  }
}, 1000);
</script>
        <?php  else :?>
            <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
            
        <?php endif;?>
            <!--<p><?= /* @escapeNotVerified */ __('We\'ll email you an order confirmation with details and tracking info.') ?></p> -->
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>
 

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
